### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by leomanlapera** [leomanlapera/tac-gatsby#1]
On some FBO pages like AMA: https://5ef000ff2ac71800078d41fb--thearnoldcos.netlify.app/tac-air/ama, please tighten up the columns so the text doesn't run into the second column https://www.dropbox.com/s/yizkpxtffs2tna8/Screenshot%202020-06-21%2023.29.31.png?dl=0

**Comment by homearanya** [comment]
https://github.com/leomanlapera/tac-gatsby/commit/0ee491769324289c71972da884318a0c87042cb2

**Comment by leomanlapera** [comment]
thank closing issue
