### ISSUE TITLE
TACenergy Map

### ISSUE THREAD

**Issue by leomanlapera** [leomanlapera/tac-gatsby#2]
Move box down and to the right so it doesn't cover the states that show selected: https://www.dropbox.com/s/4qn52jjc93qy0hc/Screenshot%202020-06-19%2010.28.55.png?dl=0

**Comment by homearanya** [comment]
https://github.com/leomanlapera/tac-gatsby/commit/d3a9da8a3baa554dfb1a20e91b2f4bef2ea16a35

**Comment by leomanlapera** [comment]
thanks closing it now
