### ISSUE TITLE
FBO Pages Blue box

### ISSUE THREAD

**Issue by leomanlapera** [leomanlapera/tac-gatsby#3]
https://www.dropbox.com/s/ra5l2puk21gwypt/Screenshot%202020-06-22%2016.27.36.png?dl=0, change text to: Need a service request? Send us all the details and we’ll take care of the rest!

**Comment by homearanya** [comment]
https://github.com/leomanlapera/tac-gatsby/commit/3e8a816efb07eb27b121941577b42555db1534e3

**Comment by leomanlapera** [comment]
@homearanya thanks
