### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by leomanlapera** [leomanlapera/tac-gatsby#5]
Upper case: https://www.dropbox.com/s/vwdf4usj6ryc85e/Screenshot%202020-06-22%2016.35.50.png?dl=0

**Comment by homearanya** [comment]
https://github.com/leomanlapera/tac-gatsby/commit/3e8a816efb07eb27b121941577b42555db1534e3

**Comment by leomanlapera** [comment]
@homearanya thanks!
