### ISSUE TITLE
Home page mobile view portrait

### ISSUE THREAD

**Issue by leomanlapera** [leomanlapera/tac-gatsby#6]
Any way to decrease the margin on the hero between the map and the headline, so we can show the brand containers below? https://www.dropbox.com/s/2fv8u65m65wkkqi/Screenshot%202020-06-22%2022.48.23.png?dl=0

**Comment by homearanya** [comment]
https://github.com/leomanlapera/tac-gatsby/commit/3e8a816efb07eb27b121941577b42555db1534e3

**Comment by leomanlapera** [comment]
thanks @homearanya
